# SecondsToSamples { #timetoalign.SecondsToSamples }

```python
SecondsToSamples(sample_rate=44100, **kwargs)
```

Convert seconds to audio samples by multiplying by sample rate.

This is a simple linear map: samples = seconds * sample_rate

Attributes:
    sample_rate: Audio sample rate in Hz.

Examples:
    >>> s2s = SecondsToSamples(sample_rate=44100)
    >>> s2s(1.0)
    44100.0
    >>> s2s(2.5)
    110250.0

    >>> # Get inverse map
    >>> samp2sec = s2s.inverse()
    >>> samp2sec(44100)
    1.0

## Attributes

| Name | Description |
| --- | --- |
| [sample_rate](#timetoalign.SecondsToSamples.sample_rate) | Audio sample rate in Hz. |

## Methods

| Name | Description |
| --- | --- |
| [from_dict](#timetoalign.SecondsToSamples.from_dict) | Deserialize from dictionary. |
| [inverse](#timetoalign.SecondsToSamples.inverse) | Return the inverse map (SamplesToSeconds). |
| [to_dict](#timetoalign.SecondsToSamples.to_dict) | Serialize to dictionary. |

### from_dict { #timetoalign.SecondsToSamples.from_dict }

```python
SecondsToSamples.from_dict(data)
```

Deserialize from dictionary.

### inverse { #timetoalign.SecondsToSamples.inverse }

```python
SecondsToSamples.inverse()
```

Return the inverse map (SamplesToSeconds).

### to_dict { #timetoalign.SecondsToSamples.to_dict }

```python
SecondsToSamples.to_dict()
```

Serialize to dictionary.
