"""Core primitives for the TimeToAlign! library.

Flat module layout (no sub-packages):

* :mod:`timetoalign.core.time` — ``TimeScalar`` base, ``Coordinate`` /
  ``Duration`` and their Id-variants (``IdCoordinate``, ``IdDuration``),
  plus the paired ``CoordinateField`` / ``IdCoordinateField`` /
  ``DurationField`` / ``IdDurationField`` field wrappers.
* :mod:`timetoalign.core.events` — pitch / harmony / Note / Measure
  scalars and their paired Fields.
* :mod:`timetoalign.core.fields` — ``DataField`` / ``SemanticField``
  hierarchy (including the raw ``NumberField`` / ``RedundantNumberField`` /
  ``DenominateNumberField`` branch), the pydantic → PyArrow translator,
  the store builder, and Parquet metadata.
* :mod:`timetoalign.core.enums` — ``Domain``, ``TimeUnit``, ``NumberType``,
  …
* :mod:`timetoalign.core.ids` — ``ScopedId``, ``IdGenerator``.
* :mod:`timetoalign.core.protocols` — pitch, harmony, and time protocols.
* :mod:`timetoalign.core.timestamp` — ``TimeStamp``, ``TimeIntervalStamp``.
"""

from __future__ import annotations

from .enums import (
    ActivationCondition,
    AgentType,
    ClaimType,
    ColumnNaming,
    ColumnRole,
    Domain,
    EventType,
    ExtrapolationPolicy,
    FancyStrEnum,
    FlowControlElement,
    FlowMode,
    IncompletePosition,
    InterpolationKind,
    IntervalPolicy,
    NumberType,
    PartitionMode,
    SupportPolicy,
    TimeUnit,
)
from .events import (
    FIGBASS_TO_INVERSION,
    DcmlHarmony,
    DcmlHarmonyField,
    DcmlStorageSchema,
    EnharmonicPitch,
    EnharmonicPitchClass,
    EnharmonicPitchClassField,
    EnharmonicPitchField,
    GenericPitch,
    GenericPitchClass,
    GenericPitchClassField,
    GenericPitchField,
    HarmonyBaseSchema,
    HarmonyLabel,
    HarmonyLabelField,
    Id,
    IdField,
    Inversion,
    Measure,
    MeasureField,
    MeasureNumber,
    MeasureNumberField,
    MidiEvent,
    MidiEventField,
    MidiPitch,
    MidiPitchField,
    Note,
    NoteField,
    PitchBasedHarmony,
    PitchBasedHarmonyField,
    RomanNumeralHarmony,
    RomanNumeralHarmonyField,
    RomanNumeralSchema,
    ScoreMidiEvent,
    ScoreMidiEventField,
    SpecificPitch,
    SpecificPitchClass,
    SpecificPitchClassField,
    SpecificPitchField,
    WesternTertianHarmony,
    WesternTertianHarmonyField,
    WesternTertianSchema,
    figbass_to_inversion,
)
from .fields import (
    TIMETOALIGN_BLOB_VERSION,
    TIMETOALIGN_METADATA_KEY,
    DataField,
    FieldVocabulary,
    FloatField,
    IntField,
    MapField,
    NumericField,
    ScalarVocabulary,
    SemanticField,
    StringField,
    StructArrayBuilder,
    StructField,
    build_struct_array,
    derive_arrow_schema,
    derive_arrow_struct,
    metadata_blob_for_model,
    metadata_blob_from_dict,
    parquet_metadata_for_model,
    parse_metadata_blob,
    register_value_projector,
    resolve_source_fields,
)
from .ids import IdGenerator, ScopedId, TimelineIdGenerator, resolve_id, resolve_ids
from .retrieval import (
    TABLE_FORMATS,
    TableFormat,
    reject_dataframe_options,
    validate_table_format,
)
from .time import (
    RATIONAL_STRUCT_TYPE,
    ROUNDING_MODES,
    Coordinate,
    CoordinateField,
    CoordinateSpec,
    CoordinateValue,
    DenominateNumber,
    DenominateNumberField,
    Duration,
    DurationField,
    DurationValue,
    IdCoordinate,
    IdCoordinateField,
    IdDuration,
    IdDurationField,
    IdTimeScalar,
    Interval,
    IntervalField,
    NumberField,
    OptionalCoordinate,
    RedundantNumberField,
    ResolvedCoordinate,
    TimeScalar,
    TimeScalarField,
    TimeScalarValue,
    build_coordinate_struct_array,
    build_number_struct_array,
    combine_number_columns,
    combine_numbers,
    coordinate_numeric_value,
    coordinate_to_struct,
    exact_coordinate_value,
    express_as,
    express_scalar_as,
    infer_number_type,
    is_rational_wire,
    number_cell,
    parse_number,
    quantize_to_unit,
    rational_to_struct,
    rational_to_wire,
    resolve_coordinate_spec,
    shift_coordinate,
    struct_to_coordinate,
    struct_to_rational,
    subtract_coordinates,
    to_canonical,
    wire_to_rational,
)
from .timestamp import (
    TimeIntervalStamp,
    TimeStamp,
    TimeStampSource,
    timestamp_table_to_dataframe,
)

__all__ = [
    # Enums
    "ActivationCondition",
    "AgentType",
    "ClaimType",
    "ColumnNaming",
    "ColumnRole",
    "Domain",
    "EventType",
    "ExtrapolationPolicy",
    "FancyStrEnum",
    "FlowControlElement",
    "FlowMode",
    "IncompletePosition",
    "InterpolationKind",
    "IntervalPolicy",
    "NumberType",
    "PartitionMode",
    "SupportPolicy",
    "TimeUnit",
    # Time scalars + paired Fields
    "Coordinate",
    "CoordinateField",
    "CoordinateSpec",
    "CoordinateValue",
    "Duration",
    "DurationField",
    "DurationValue",
    "IdCoordinate",
    "IdCoordinateField",
    "IdDuration",
    "IdDurationField",
    "IdTimeScalar",
    "Interval",
    "IntervalField",
    "OptionalCoordinate",
    "ResolvedCoordinate",
    "TimeScalar",
    "TimeScalarField",
    "TimeScalarValue",
    "resolve_coordinate_spec",
    "struct_to_coordinate",
    # DataField hierarchy / schema mechanism
    "DataField",
    "FloatField",
    "IntField",
    "MapField",
    "NumericField",
    "StringField",
    "StructField",
    # Raw numeric struct branch
    "NumberField",
    "RedundantNumberField",
    "DenominateNumberField",
    # Semantic bridge + store builder + translator helpers
    "SemanticField",
    "StructArrayBuilder",
    "RATIONAL_STRUCT_TYPE",
    "FieldVocabulary",
    "ScalarVocabulary",
    "TIMETOALIGN_BLOB_VERSION",
    "TIMETOALIGN_METADATA_KEY",
    "build_coordinate_struct_array",
    "build_struct_array",
    "coordinate_to_struct",
    "derive_arrow_schema",
    "derive_arrow_struct",
    "is_rational_wire",
    "metadata_blob_for_model",
    "metadata_blob_from_dict",
    "parquet_metadata_for_model",
    "parse_metadata_blob",
    "rational_to_struct",
    "rational_to_wire",
    "register_value_projector",
    "resolve_source_fields",
    "struct_to_rational",
    "struct_to_coordinate",
    "wire_to_rational",
    # Pitch scalars + paired Fields
    "EnharmonicPitch",
    "EnharmonicPitchClass",
    "EnharmonicPitchClassField",
    "EnharmonicPitchField",
    "GenericPitch",
    "GenericPitchClass",
    "GenericPitchClassField",
    "GenericPitchField",
    "MidiPitch",
    "MidiPitchField",
    "SpecificPitch",
    "SpecificPitchClass",
    "SpecificPitchClassField",
    "SpecificPitchField",
    # Harmony scalars + paired Fields
    "DcmlHarmony",
    "DcmlHarmonyField",
    "DcmlStorageSchema",
    "FIGBASS_TO_INVERSION",
    "HarmonyBaseSchema",
    "HarmonyLabel",
    "HarmonyLabelField",
    "Inversion",
    "PitchBasedHarmony",
    "PitchBasedHarmonyField",
    "RomanNumeralHarmony",
    "RomanNumeralHarmonyField",
    "RomanNumeralSchema",
    "WesternTertianHarmony",
    "WesternTertianHarmonyField",
    "WesternTertianSchema",
    "figbass_to_inversion",
    # Event scalars + paired Fields
    "Id",
    "IdField",
    "Measure",
    "MeasureField",
    "MeasureNumber",
    "MeasureNumberField",
    "MidiEvent",
    "MidiEventField",
    "Note",
    "NoteField",
    "ScoreMidiEvent",
    "ScoreMidiEventField",
    # Timestamps
    "TimeStamp",
    "TimeIntervalStamp",
    "TimeStampSource",
    "timestamp_table_to_dataframe",
    # Retrieval vocabularies
    "TableFormat",
    "TABLE_FORMATS",
    "validate_table_format",
    "reject_dataframe_options",
    # IDs
    "ScopedId",
    "IdGenerator",
    "TimelineIdGenerator",
    "resolve_id",
    "resolve_ids",
    "DenominateNumber",
    "ROUNDING_MODES",
    "build_number_struct_array",
    "combine_number_columns",
    "combine_numbers",
    "coordinate_numeric_value",
    "exact_coordinate_value",
    "infer_number_type",
    "number_cell",
    "quantize_to_unit",
    "shift_coordinate",
    "subtract_coordinates",
    "to_canonical",
    "parse_number",
    "express_as",
    "express_scalar_as",
]
