"""MIDI constants and lookup tables."""

from __future__ import annotations

# Control Change number to human-readable purpose
CC_PURPOSE: dict[int, str] = {
    0: "Bank Select (MSB)",
    1: "Modulation Wheel (MSB)",
    2: "Breath Controller (MSB)",
    3: "Undefined (MSB)",
    4: "Foot Controller (MSB)",
    5: "Portamento Time (MSB)",
    6: "Data Entry (MSB)",
    7: "Channel Volume (MSB)",
    8: "Balance (MSB)",
    9: "Undefined (MSB)",
    10: "Pan (MSB)",
    11: "Expression Controller (MSB)",
    12: "Effect Control 1 (MSB)",
    13: "Effect Control 2 (MSB)",
    14: "Undefined (MSB)",
    15: "Undefined (MSB)",
    16: "General Purpose Controller 1 (MSB)",
    17: "General Purpose Controller 2 (MSB)",
    18: "General Purpose Controller 3 (MSB)",
    19: "General Purpose Controller 4 (MSB)",
    20: "Undefined (MSB)",
    21: "Undefined (MSB)",
    22: "Undefined (MSB)",
    23: "Undefined (MSB)",
    24: "Undefined (MSB)",
    25: "Undefined (MSB)",
    26: "Undefined (MSB)",
    27: "Undefined (MSB)",
    28: "Undefined (MSB)",
    29: "Undefined (MSB)",
    30: "Undefined (MSB)",
    31: "Undefined (MSB)",
    32: "Bank Select (LSB)",
    33: "Modulation Wheel (LSB)",
    34: "Breath Controller (LSB)",
    35: "Undefined (LSB)",
    36: "Foot Controller (LSB)",
    37: "Portamento Time (LSB)",
    38: "Data Entry (LSB)",
    39: "Channel Volume (LSB)",
    40: "Balance (LSB)",
    41: "Undefined (LSB)",
    42: "Pan (LSB)",
    43: "Expression Controller (LSB)",
    44: "Effect Control 1 (LSB)",
    45: "Effect Control 2 (LSB)",
    46: "Undefined (LSB)",
    47: "Undefined (LSB)",
    48: "General Purpose Controller 1 (LSB)",
    49: "General Purpose Controller 2 (LSB)",
    50: "General Purpose Controller 3 (LSB)",
    51: "General Purpose Controller 4 (LSB)",
    52: "Undefined (LSB)",
    53: "Undefined (LSB)",
    54: "Undefined (LSB)",
    55: "Undefined (LSB)",
    56: "Undefined (LSB)",
    57: "Undefined (LSB)",
    58: "Undefined (LSB)",
    59: "Undefined (LSB)",
    60: "Undefined (LSB)",
    61: "Undefined (LSB)",
    62: "Undefined (LSB)",
    63: "Undefined (LSB)",
    64: "Sustain Pedal",
    65: "Portamento",
    66: "Sostenuto Pedal",
    67: "Soft Pedal",
    68: "Legato Footswitch",
    69: "Hold 2 Pedal",
    70: "Sound Variation",
    71: "Resonance (Timbre)",
    72: "Release Time",
    73: "Attack Time",
    74: "Brightness (Filter Cutoff)",
    75: "Sound Controller 6",
    76: "Sound Controller 7",
    77: "Sound Controller 8",
    78: "Sound Controller 9",
    79: "Sound Controller 10",
    80: "General Purpose Controller 5",
    81: "General Purpose Controller 6",
    82: "General Purpose Controller 7",
    83: "General Purpose Controller 8",
    84: "Portamento Control",
    85: "Undefined",
    86: "Undefined",
    87: "Undefined",
    88: "High Resolution Velocity Prefix",
    89: "Undefined",
    90: "Undefined",
    91: "Effects 1 Depth (Reverb Send Level)",
    92: "Effects 2 Depth (Tremolo Depth)",
    93: "Effects 3 Depth (Chorus Depth)",
    94: "Effects 4 Depth (Detune Depth)",
    95: "Effects 5 Depth (Phaser Depth)",
    96: "Data Increment",
    97: "Data Decrement",
    98: "Non-Registered Parameter Number (NRPN) LSB",
    99: "Non-Registered Parameter Number (NRPN) MSB",
    100: "Registered Parameter Number (RPN) LSB",
    101: "Registered Parameter Number (RPN) MSB",
    102: "Undefined",
    103: "Undefined",
    104: "Undefined",
    105: "Undefined",
    106: "Undefined",
    107: "Undefined",
    108: "Undefined",
    109: "Undefined",
    110: "Undefined",
    111: "Undefined",
    112: "Undefined",
    113: "Undefined",
    114: "Undefined",
    115: "Undefined",
    116: "Undefined",
    117: "Undefined",
    118: "Undefined",
    119: "Undefined",
    120: "All Sound Off",
    121: "Reset All Controllers",
    122: "Local Control",
    123: "All Notes Off",
    124: "Omni Mode Off",
    125: "Omni Mode On",
    126: "Mono Mode (Poly Off)",
    127: "Poly Mode (Mono Off)",
}


class MidiEventType:
    """String constants for MIDI event types."""

    NOTE = "Note"
    CONTROL_CHANGE = "ControlChange"
    PROGRAM_CHANGE = "ProgramChange"
    TEMPO_CHANGE = "TempoChange"
    TIME_SIGNATURE = "TimeSignature"
    KEY_SIGNATURE = "KeySignature"
